name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
- repo: self
trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - templates/*
    - .azure-devops/template-ci.yaml
pool:
  name: Hosted Windows 2019 with VS2019
steps:
- bash: 'npm install -g ajv-cli'
  displayName: 'Install JSON validation utility'

- bash: 'ajv validate -s templates/schemas/template.json -d templates/manifest.json'
  displayName: 'Validate Manifest'

- bash: 'ajv validate -s templates/schemas/manifest.json -d templates/*.json'
  displayName: 'Validate Templates'